# Download from: https://www.kaggle.com/datasets/swayamsinghal/slang-txt  &&  https://www.kaggle.com/datasets/ckapre51/common-abbreviations-and-short-forms-with-meanings


slang_text_dict = {
    'abt': 'about',
    'abt2': 'about to',
    'acc': 'actually',
    'add': 'address',
    'afaik': 'as far as i know',
    'afk': 'away from keyboard',
    'aka': 'also known as',
    'asap': 'as soon as possible',
    'asf': 'as f***',
    'asl': 'age, sex, location',
    'atm': 'at the moment',
    'bb': 'babe',
    'b4': 'before',
    'bc': 'because',
    'bet': 'okay; affirming something',
    'bday': 'birthday',
    'blates': 'obviously',
    'bf': 'boyfriend',
    'bffl': 'best friends for life',
    'nc': 'nice',
    'bff': 'best friends forever',
    'boyf': 'boyfriend',
    'brb': 'be right back',
    'btw': 'by the way',
    'cap': 'lie',
    'cba': "can't be bothered",
    'cmb': 'call me back',
    'cmon': 'come on',
    'ctn': "can't talk now",
    'cu': 'see you',
    'cua': 'see you around',
    'cul': 'see you later',
    'cya': 'see ya',
    'diss': 'disrespect',
    'dkdc': "don't know",
    'dl': 'download',
    'dm': 'direct message, a form of private messaging',
    'dnt': "don't",
    'ema': 'email address',
    'eta': 'estimated time of arrival',
    'ez': 'easy',
    'f': 'female',
    'fam': "short for 'family', similar to 'bro'",
    'faq': 'frequently asked questions',
    'fb': 'facebook',
    'finna': "i'm going to",
    'fire': 'a word to describe something positive',
    'fr': 'for real',
    'fuq': 'f***',
    'fuqn': 'f***ing',
    'fwb': 'friends with benefits',
    'fwd': 'forward',
    'fyi': 'for your information',
    'g': 'gay',
    'g2cu': 'good to see you',
    'g2g': 'got to go',
    'g2r': 'got to run',
    'gamer': 'video game player',
    'gf': 'girlfriend',
    'gg': 'good game',
    'gj': 'good job',
    'gl': 'good luck',
    'glhf': 'good luck have fun',
    'goat': 'greatest of all time',
    'gnite': 'good night',
    'gr8': 'great',
    'gratz': 'congratulations',
    'gtfoh': 'get the f*** outta here',
    'gtg': 'got to go',
    'gud': 'good',
    'gyat': "referencing the size of someone's back end",
    'h8': 'hate',
    'hella': 'really',
    'hits different': 'something that affects you in a particular way',
    'hv': 'have',
    'hw': 'homework',
    'hbd': 'happy birthday',
    'ib': "i'm back",
    'ic': 'i see',
    'idc': "i don't care",
    'idk': "i don't know",
    'ig': 'i guess or instagram',
    'iirc': 'if i remember correctly',
    'ikr': 'i know right?',
    'ilu': 'i love you',
    'ily': 'i love you',
    'im': 'instant message',
    'imho': 'in my humble opinion',
    'imo': 'in my opinion',
    'insta': 'instagram',
    'irl': 'in real life',
    "it's giving": 'used to describe something',
    'iykyk': 'if you know, you know',
    'jk': 'just kidding',
    'k': 'okay',
    'kewl': 'cool',
    'kthnx': 'ok, thanks',
    'l': 'lesbian',
    'take the l': 'loss',
    'l8': 'late',
    'l8r': 'later',
    'let them cook': 'give someone time and space to do something you know they can do',
    'lit': 'it describes something as positive',
    'lmao': 'laughing my a** off',
    'lol': 'laugh out loud',
    'lolll': 'laugh out loud a lot',
    'luv ya': 'love you',
    'm': 'male',
    'm.i.r.l': 'meet in real life',
    'mkay': 'mmm, okay',
    'mmo': 'massively multiplayer online',
    'mmorpg': 'massively multiplayer online role-playing game',
    'msg': 'message',
    'mwah': 'to give a kiss',
    'nan': 'not available',
    'n2m': 'nothing too much',
    'nbd': 'no big deal',
    'ne': 'any',
    'ne1': 'anyone',
    'nm': 'never mind',
    'no cap': 'no lie',
    'noob': 'inexperienced gamer',
    'np': 'no problem',
    'nthng': 'nothing',
    'nvr': 'never',
    'nw': 'no worries',
    'oic': 'oh, i see',
    'om': 'oh my',
    'omg': 'oh my god',
    'omw': 'on my way',
    'iu': 'i love you',
    'onl': 'online',
    'ot': 'off topic',
    'ova': 'over',
    'peak': 'unfortunate',
    'peeps': 'people',
    'pic': 'picture',
    'pir': 'parent in room',
    'pk': 'player kill',
    'pls': 'please',
    'plz': 'please',
    'pm': 'private message',
    'pmsl': 'peeing myself laughing',
    'pov': 'point of view',
    'ppl': 'people',
    'prolly': 'probably',
    'pwn': 'own, as in conquer or defeat',
    'pwned': 'owned, as in conquered or defeated',
    'qt': 'cutie',
    'qtpi': 'cutie pie',
    'r': 'are or our',
    'riz/rizz': 'charisma',
    'rizzler': 'someone who is good at flirting because they have rizz',
    'rly': 'really',
    'rofl': 'rolling on the floor laughing',
    'rpg': 'role playing game',
    'ru': 'are you?',
    'ruok': 'are you okay?',
    'sec': 'second',
    'seggs': 'sex',
    'ship': 'imagining people together',
    'simp': 'someone who does too much for their crush often used in sexist context against men',
    'simping': ' someone who does too much for their crush often used in sexist context against men',
    'skibidi': 'a reference to a video about an army of toilets taking over the world',
    'skl': 'school',
    'sksksk': 'laughter sounds',
    'slaps': 'describing something as good',
    'smh': 'shaking my head',
    'sms': 'short message service',
    'so': 'significant other',
    'sob': 'son of a b*tch',
    'sos': 'help',
    'spk': 'speak',
    'srs': 'serious',
    'srsbsns': 'serious business',
    'srsly': 'seriously',
    'sry': 'sorry',
    'stan': 'being a fan of someone',
    'str8': 'straight',
    'sup': "what's up",
    'sus': 'suspicious',
    'sux': 'it sucks',
    'swag': "boasting about one's skills or style",
    'tbh': 'to be honest',
    'tc': 'take care',
    'tea': 'gossip',
    'tgif': "thank god it's friday",
    'thanq': 'thank you',
    'thx': 'thanks',
    'tmi': 'too much information',
    'trans': 'transsexual',
    't*': 'transsexual',
    't+': 'transsexual',
    'ttfn': 'ta-ta for now',
    'ttyl': 'talk to you later',
    'tweet': 'twitter post',
    'txt': 'text',
    'ty': 'thank you',
    'u': 'you',
    'u2': 'you too',
    'ul': 'upload',
    'unalive': 'kill',
    'ur': "you are",
    'vm': 'voicemail',
    'w': 'win',
    'w@': 'what?',
    'w/': 'with',
    'w/e': 'whatever',
    'w/o': 'without',
    'w8': 'wait',
    'wag1': "what's up",
    'wbu': 'what about you?',
    'wk': 'week',
    'wrk': 'work',
    'wtf': 'what the f***',
    'wtg': 'way to go',
    'wyd': 'what are you doing?',
    'wysiwyg': 'what you see is what you get',
    'x': 'kiss',
    'y?': 'why?',
    'yeet': 'to throw something',
    'yktv': 'you know the vibe',
    'yolo': 'you only live once',
    'yr': 'your',
    'yw': "you're welcome",
    'gen z': 'people born from around 1997-2012',
    'za': 'pizza',
    '2': 'to',
    '24/7': 'twenty-four hours a day, seven days a week',
    "$" : " dollar ",
    "€" : " euro ",
    "4ao" : "for adults only",
    "a.m" : "before midday",
    "a3" : "anytime anywhere anyplace",
    "aamof" : "as a matter of fact",
    "acct" : "account",
    "adih" : "another day in hell",
    "afaic" : "as far as i am concerned",
    "afaict" : "as far as i can tell",
    "afaik" : "as far as i know",
    "afair" : "as far as i remember",
    "afk" : "away from keyboard",
    "app" : "application",
    "approx" : "approximately",
    "apps" : "applications",
    "asap" : "as soon as possible",
    "asl" : "age, sex, location",
    "atk" : "at the keyboard",
    "ave." : "avenue",
    "aymm" : "are you my mother",
    "ayor" : "at your own risk", 
    "b&b" : "bed and breakfast",
    "b+b" : "bed and breakfast",
    "b.c" : "before christ",
    "b2b" : "business to business",
    "b2c" : "business to customer",
    "b4" : "before",
    "b4n" : "bye for now",
    "b@u" : "back at you",
    "bae" : "before anyone else",
    "bak" : "back at keyboard",
    "bbbg" : "bye bye be good",
    "bbc" : "british broadcasting corporation",
    "bbias" : "be back in a second",
    "bbl" : "be back later",
    "bbs" : "be back soon",
    "be4" : "before",
    "bfn" : "bye for now",
    "blvd" : "boulevard",
    "bout" : "about",
    "brb" : "be right back",
    "bros" : "brothers",
    "brt" : "be right there",
    "bsaaw" : "big smile and a wink",
    "btw" : "by the way",
    "bwl" : "bursting with laughter",
    "c/o" : "care of",
    "cet" : "central european time",
    "cf" : "compare",
    "cia" : "central intelligence agency",
    "csl" : "can not stop laughing",
    "cu" : "see you",
    "cul8r" : "see you later",
    "cv" : "curriculum vitae",
    "cwot" : "complete waste of time",
    "cya" : "see you",
    "cyt" : "see you tomorrow",
    "dae" : "does anyone else",
    "dbmib" : "do not bother me i am busy",
    "diy" : "do it yourself",
    "dm" : "direct message",
    "dwh" : "during work hours",
    "e123" : "easy as one two three",
    "eet" : "eastern european time",
    "eg" : "example",
    "embm" : "early morning business meeting",
    "encl" : "enclosed",
    "encl." : "enclosed",
    "etc" : "and so on",
    "faq" : "frequently asked questions",
    "fawc" : "for anyone who cares",
    "fb" : "facebook",
    "fc" : "fingers crossed",
    "fig" : "figure",
    "fimh" : "forever in my heart", 
    "ft." : "feet",
    "ft" : "featuring",
    "ftl" : "for the loss",
    "ftw" : "for the win",
    "fwiw" : "for what it is worth",
    "fyi" : "for your information",
    "g9" : "genius",
    "gahoy" : "get a hold of yourself",
    "gal" : "get a life",
    "gcse" : "general certificate of secondary education",
    "gfn" : "gone for now",
    "gg" : "good game",
    "gl" : "good luck",
    "glhf" : "good luck have fun",
    "gmt" : "greenwich mean time",
    "gmta" : "great minds think alike",
    "gn" : "good night",
    "g.o.a.t" : "greatest of all time",
    "goat" : "greatest of all time",
    "goi" : "get over it",
    "gps" : "global positioning system",
    "gr8" : "great",
    "gratz" : "congratulations",
    "gyal" : "girl",
    "h&c" : "hot and cold",
    "hp" : "horsepower",
    "hr" : "hour",
    "hrh" : "his royal highness",
    "ht" : "height",
    "ibrb" : "i will be right back",
    "ic" : "i see",
    "icq" : "i seek you",
    "icymi" : "in case you missed it",
    "idc" : "i do not care",
    "idgadf" : "i do not give a damn fuck",
    "idgaf" : "i do not give a fuck",
    "idk" : "i do not know",
    "ie" : "that is",
    "i.e" : "that is",
    "ifyp" : "i feel your pain",
    "IG" : "instagram",
    "iirc" : "if i remember correctly",
    "ilu" : "i love you",
    "imho" : "in my humble opinion",
    "imo" : "in my opinion",
    "imu" : "i miss you",
    "iow" : "in other words",
    "irl" : "in real life",
    "j4f" : "just for fun",
    "jic" : "just in case",
    "jk" : "just kidding",
    "jsyk" : "just so you know",
    "l8r" : "later",
    "lb" : "pound",
    "lbs" : "pounds",
    "ldr" : "long distance relationship",
    "lmao" : "laugh my ass off",
    "lmfao" : "laugh my fucking ass off",
    "lol" : "laughing out loud",
    "ltd" : "limited",
    "ltns" : "long time no see",
    "m8" : "mate",
    "mf" : "motherfucker",
    "mfs" : "motherfuckers",
    "mfw" : "my face when",
    "mofo" : "motherfucker",
    "mph" : "miles per hour",
    "mr" : "mister",
    "mrw" : "my reaction when",
    "ms" : "miss",
    "mte" : "my thoughts exactly",
    "nagi" : "not a good idea",
    "nbc" : "national broadcasting company",
    "nbd" : "not big deal",
    "nfs" : "not for sale",
    "ngl" : "not going to lie",
    "nhs" : "national health service",
    "nrn" : "no reply necessary",
    "nsfl" : "not safe for life",
    "nsfw" : "not safe for work",
    "nth" : "nice to have",
    "nvr" : "never",
    "nyc" : "new york city",
    "oc" : "original content",
    "og" : "original",
    "ohp" : "overhead projector",
    "oic" : "oh i see",
    "omdb" : "over my dead body",
    "omg" : "oh my god",
    "omw" : "on my way",
    "p.a" : "per annum",
    "p.m" : "after midday",
    "pm" : "prime minister",
    "poc" : "people of color",
    "pov" : "point of view",
    "pp" : "pages",
    "ppl" : "people",
    "prw" : "parents are watching",
    "ps" : "postscript",
    "pt" : "point",
    "ptb" : "please text back",
    "pto" : "please turn over",
    "qpsa" : "what happens", #"que pasa",
    "ratchet" : "rude",
    "rbtl" : "read between the lines",
    "rlrt" : "real life retweet", 
    "rofl" : "rolling on the floor laughing",
    "roflol" : "rolling on the floor laughing out loud",
    "rotflmao" : "rolling on the floor laughing my ass off",
    "rt" : "retweet",
    "ruok" : "are you ok",
    "sfw" : "safe for work",
    "sk8" : "skate",
    "smh" : "shake my head",
    "sq" : "square",
    "srsly" : "seriously", 
    "ssdd" : "same stuff different day",
    "tbh" : "to be honest",
    "tbs" : "tablespooful",
    "tbsp" : "tablespooful",
    "tfw" : "that feeling when",
    "thks" : "thank you",
    "tho" : "though",
    "thx" : "thank you",
    "tia" : "thanks in advance",
    "til" : "today i learned",
    "tl;dr" : "too long i did not read",
    "tldr" : "too long i did not read",
    "tmb" : "tweet me back",
    "tntl" : "trying not to laugh",
    "ttyl" : "talk to you later",
    "u" : "you",
    "u2" : "you too",
    "u4e" : "yours for ever",
    "utc" : "coordinated universal time",
    "w/" : "with",
    "w/o" : "without",
    "w8" : "wait",
    "wassup" : "what is up",
    "wb" : "welcome back",
    "wtf" : "what the fuck",
    "wtg" : "way to go",
    "wtpa" : "where the party at",
    "wuf" : "where are you from",
    "wuzup" : "what is up",
    "wywh" : "wish you were here",
    "yd" : "yard",
    "ygtr" : "you got that right",
    "ynk" : "you never know",
    "zzz" : "sleeping bored and tired"
}